# Github workflow
name: CI-CHECK

# run when push commits
on:
  push:
    branches: [ dev ]  
  pull_request:
    branches: [ dev ]

# Jobs
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out the Repo
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Docker Build
        run: |
          docker build -t test .
